rtc: pcf85053: Fix unused variable warning
Remove an unused variable to fix the compile warning:

drivers/rtc/rtc-pcf85053.c: In function 'pcf85053_rtc_probe':
drivers/rtc/rtc-pcf85053.c:65:13: error: unused variable 'rc' [-Werror=unused-variable]
   65 |         int rc;
      |             ^~

Signed-off-by: Iwona Winiarska <iwona.winiarska@intel.com>