hwmon: pmbus: smart: Fix unused variable warning
Remove an unused variable to fix the compile warning:

drivers/hwmon/pmbus/smart.c: In function 'smart_read_word':
drivers/hwmon/pmbus/smart.c:264:13: error: unused variable 'result' [-Werror=unused-variable]
  264 |         u16 result;
      |             ^~~~~~

Signed-off-by: Iwona Winiarska <iwona.winiarska@intel.com>